### ISSUE TITLE
SOLVED: webpack installation errors

### ISSUE THREAD

**Issue by artiste1212** [PacktPublishing/Modernizing-Drupal-10-Theme-Development#29]
I tried to follow the command for installing webpack using the command `node_modules/.bin/webpack --config webpack.config.js --mode development`. I got two errors -- I got the following output:

`asset main.js 10.5 KiB [emitted] (name: main) 1 related asset
runtime modules 937 bytes 4 modules
orphan modules 39 bytes [orphan] 1 module
cacheable modules 68 bytes
  ./js/main.js 29 bytes [built] [code generated]
  ./css/tailwind.css 39 bytes [built] [code generated] [1 error]

ERROR in ./css/tailwind.css (./css/tailwind.css.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js!./css/tailwind.css)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/cosmiconfig/dist/index.js:78
    if (metaConfig.config?.loaders) {
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/postcss-loader/dist/utils.js:18:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
 @ ./css/tailwind.css
 @ ./js/main.js 1:0-29

ERROR in ./css/tailwind.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/cosmiconfig/dist/index.js:78
    if (metaConfig.config?.loaders) {
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/postcss-loader/dist/utils.js:18:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at tryRunOrWebpackError (/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/webpack/lib/HookWebpackError.js:88:9)
    at __webpack_require_module__ (/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/webpack/lib/Compilation.js:5067:12)
    at __webpack_require__ (/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/webpack/lib/Compilation.js:5024:18)
    at /home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/webpack/lib/Compilation.js:5095:20
    at symbolIterator (/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/neo-async/async.js:3485:9)
    at done (/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/neo-async/async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/tapable/lib/Hook.js:18:14)
    at /home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/webpack/lib/Compilation.js:5002:43
    at symbolIterator (/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/neo-async/async.js:3482:9)
-- inner error --
Error: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/cosmiconfig/dist/index.js:78
    if (metaConfig.config?.loaders) {
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/postcss-loader/dist/utils.js:18:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.<anonymous> (/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/css-loader/dist/cjs.js!/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/postcss-loader/dist/cjs.js!/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/css/tailwind.css:1:7)
    at /home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:452:10
    at Hook.eval [as call] (eval at create (/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:5:1)
    at Hook.CALL_DELEGATE [as _call] (/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/tapable/lib/Hook.js:14:14)
    at /home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/webpack/lib/Compilation.js:5069:39
    at tryRunOrWebpackError (/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/webpack/lib/HookWebpackError.js:83:7)
    at __webpack_require_module__ (/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/webpack/lib/Compilation.js:5067:12)
    at __webpack_require__ (/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/webpack/lib/Compilation.js:5024:18)
    at /home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/webpack/lib/Compilation.js:5095:20
    at symbolIterator (/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/neo-async/async.js:3485:9)

Generated code for /home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/css-loader/dist/cjs.js!/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/postcss-loader/dist/cjs.js!/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/css/tailwind.css
1 | throw new Error("Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):\n/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/cosmiconfig/dist/index.js:78\n    if (metaConfig.config?.loaders) {\n                          ^\n\nSyntaxError: Unexpected token '.'\n    at wrapSafe (internal/modules/cjs/loader.js:915:16)\n    at Module._compile (internal/modules/cjs/loader.js:963:27)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Module.load (internal/modules/cjs/loader.js:863:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:708:14)\n    at Module.require (internal/modules/cjs/loader.js:887:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips/node_modules/postcss-loader/dist/utils.js:18:20)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)");
 @ ./js/main.js 1:0-29

webpack 5.89.0 compiled with 2 errors in 263 ms`

How can I fix this?

**Comment by murrwood** [comment]
Suggest that you try using the ddev shell.

That is:
ddev ssh

then change to the alps_trips directory
then try the command again

**Comment by artiste1212** [comment]
Hmmmm. I can't seen to find the alps_trips directory when I'm in ddev ssh. When I'm not in ddev ssh, this directory is located at the path /home/lostroots/Modernizing-Drupal-10-Theme-Development/web/themes/custom/alps_trips. However, when I'm in ddev ssh, the /home/lostroots directory does not contain any subdirectories at all. It only contains two files: README.txt and bash_aliases.example.

**Comment by murrwood** [comment]
Sounds like your ddev ssh is pointing to somewhere in left field.   Try this:

ddev ssh
Change to your Modernizing-Drupal-10... directory      cd /var/www/html 
Make sure you are in the correct directory    ls -la
Change to the alps_trips directory   cd web/themes/custom/alps_trips
Run the command again

**Comment by artiste1212** [comment]
Thanks! That seems to have worked... I didn't realize that /var/www/html from within ddev ssh was the same as /home/lostroots/Modernizing-Drupal-10-Theme-Development from outside of ddev ssh, so I had no idea how to find the correct directory.

**Comment by lussoluca** [comment]
There is a note on page 10 that says:

```
Note
The folder that contains the website is mounted into the web container. The files are exactly the
same, but they can be accessed from your local computer and from the web container. Bear in
mind that the absolute path may be different between the two systems. On your local computer,
it will be something such as /Users/lussoluca/Sites/modern_drupal_themes,
but on the web container, it will always be /var/www/html. You can connect to a shell that
runs in the web container using the ddev ssh command. To close the web container shell
and return to the host shell, just type exit and hit Return.
```

Probably you've missed it :-)

Do you think I should rewrite this to be more clear?

**Comment by artiste1212** [comment]
Thanks. I think I could have used a little bit more background information on what exactly ddev ssh does. As a more or less beginner, I was viewing it as an abstraction. I didn't have the conceptual understanding that ddev ssh had anything to do with "the folder that contains this website" or a "web container." I'm assuming that this would be clear to most of your readers.

**Comment by artiste1212** [comment]
In retrospect, I can see that this is exactly what the note says. I guess either I just didn't quite understand it, or else I had forgotten by the time I was trying to figure it out.

**Comment by selwynpolit** [comment]
Hmmm. I'm getting a different set of error regardless of whether I do `ddev ssh` or run it on the host:



`spolit@packt-web:/var/www/html/web/themes/custom/alps_trips$ node_modules/.bin/webpack --config webpack.config.js --mode development
[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'modules'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, experiments?, extends?, externals?, externalsPresets?, externalsType?, ignoreWarnings?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, snapshot?, stats?, target?, watch?, watchOptions? }
   -> Options object as provided by the user.
   For typos: please correct them.
   For loader options: webpack >= v2.0.0 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           modules: …
         }
       })
     ]
`

This is my webpack.config.js

`
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const path = require('path');
module.exports = {
  mode: 'production',
  entry: "./js/main.js",
  devtool: 'source-map',
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, './build')
  },
  modules: {
    rules: [
      {
        test: /\.css$/,
        use: [
          MiniCssExtractPlugin.loader,
          "css-loader",
          "postcss-loader",
        ]
      }
    ]
  },
  plugins: [
    new MiniCssExtractPlugin({
      filename: 'styles.css',
    }),
  ]
};
`

**Comment by selwynpolit** [comment]
and after updating the webpack.config.js file from the final branch of this repo, I now get the following:

```
spolit@packt-web:/var/www/html/web/themes/custom/alps_trips$ node_modules/.bin/webpack --config webpack.config.js --mode development
asset main.js 1.1 KiB [emitted] (name: main) 1 related asset
runtime modules 274 bytes 1 module
./js/main.js 59 bytes [built] [code generated]

ERROR in ./js/main.js 1:0-29
Module not found: Error: Can't resolve '../css/tailwind.css' in '/var/www/html/web/themes/custom/alps_trips/js'
resolve '../css/tailwind.css' in '/var/www/html/web/themes/custom/alps_trips/js'
  using description file: /var/www/html/web/themes/custom/alps_trips/package.json (relative path: ./js)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /var/www/html/web/themes/custom/alps_trips/package.json (relative path: ./css/tailwind.css)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /var/www/html/web/themes/custom/alps_trips/css/tailwind.css doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /var/www/html/web/themes/custom/alps_trips/css/tailwind.css.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /var/www/html/web/themes/custom/alps_trips/css/tailwind.css.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /var/www/html/web/themes/custom/alps_trips/css/tailwind.css.wasm doesn't exist
      as directory
        /var/www/html/web/themes/custom/alps_trips/css/tailwind.css doesn't exist

webpack 5.90.3 compiled with 1 error in 42 ms
```
I think I may be getting closer...
