### ISSUE TITLE
Chapter 2 Page 36

### ISSUE THREAD

**Issue by pikadroo** [PacktPublishing/Modernizing-Drupal-10-Theme-Development#39]
I am not sure where it was mentioned that I should do something with the files that are missing after running node_modules. I never saw that I was told to make those files so should they have been generated. See I don't understand because I don't even get a simplest explanation sometimes of what these commands are doing.

packt-web:/var/www/html/web/themes/custom/alps_trips$ node_modules/.bin/webpack --config webpack.config.js --mode development
asset main.js 1.07 KiB [compared for emit] (name: main) 1 related asset
runtime modules 274 bytes 1 module
./js/main.js 30 bytes [built] [code generated]

ERROR in ./js/main.js 1:0-29
Module not found: Error: Can't resolve '../css/tailwind.css' in '/var/www/html/web/themes/custom/alps_trips/js'
resolve '../css/tailwind.css' in '/var/www/html/web/themes/custom/alps_trips/js'
  using description file: /var/www/html/web/themes/custom/alps_trips/package.json (relative path: ./js)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /var/www/html/web/themes/custom/alps_trips/package.json (relative path: ./css/tailwind.css)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /var/www/html/web/themes/custom/alps_trips/css/tailwind.css doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /var/www/html/web/themes/custom/alps_trips/css/tailwind.css.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /var/www/html/web/themes/custom/alps_trips/css/tailwind.css.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /var/www/html/web/themes/custom/alps_trips/css/tailwind.css.wasm doesn't exist
      as directory
        /var/www/html/web/themes/custom/alps_trips/css/tailwind.css doesn't exist

webpack 5.89.0 compiled with 1 error in 46 ms

**Comment by pikadroo** [comment]
I am also getting this error on postcss-loader

error postcss-loader@8.0.0: The engine "node" is incompatible with this module. Expected version ">= 18.12.0". Got "16.20.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by pikadroo** [comment]
node_modules/.bin/webpack --config webpack.config.js --mode development

Should generate /build and the files main.js, main.js.map, styles.css, and styles.css.map but of course it does not I only get main.js and main.js.map because it appears tailwind.css, tailwind.css.js, tailwind.css.json, tailwind.css.wasm do not exist in /css and I have no clue where I am supposed to get them from. If none of these commands did anything to create them up till now and the files don’t already come with everything in git I am not sure what I am supposed to do.

**Comment by pikadroo** [comment]
Ok so clearly I discovered the error with tailwind.css and now I get the following keeping in mind I had to ignore the version issue on postcss-loader:

packt-web:/var/www/html/web/themes/custom/alps_trips$ node_modules/.bin/webpack --config webpack.config.js --mode development
asset main.js 9.35 KiB [emitted] (name: main) 1 related asset
runtime modules 937 bytes 4 modules
orphan modules 39 bytes [orphan] 1 module
cacheable modules 68 bytes
  ./js/main.js 29 bytes [built] [code generated]
  ./css/tailwind.css 39 bytes [built] [code generated] [1 error]

ERROR in ./css/tailwind.css (./css/tailwind.css.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js!./css/tailwind.css)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
ReferenceError: tailwindcss is not defined
    at Object.<anonymous> (/var/www/html/web/themes/custom/alps_trips/postcss.config.js:3:14)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at module.exports (/var/www/html/web/themes/custom/alps_trips/node_modules/import-fresh/index.js:32:59)
    at Object.loadJsSync (/var/www/html/web/themes/custom/alps_trips/node_modules/cosmiconfig/dist/loaders.js:17:12)
    at .js (/var/www/html/web/themes/custom/alps_trips/node_modules/postcss-loader/dist/utils.js:61:56)
    at Explorer.#loadConfiguration (/var/www/html/web/themes/custom/alps_trips/node_modules/cosmiconfig/dist/Explorer.js:116:42)
 @ ./css/tailwind.css
 @ ./js/main.js 1:0-29

ERROR in ./css/tailwind.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
ReferenceError: tailwindcss is not defined
    at Object.<anonymous> (/var/www/html/web/themes/custom/alps_trips/postcss.config.js:3:14)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at module.exports (/var/www/html/web/themes/custom/alps_trips/node_modules/import-fresh/index.js:32:59)
    at Object.loadJsSync (/var/www/html/web/themes/custom/alps_trips/node_modules/cosmiconfig/dist/loaders.js:17:12)
    at .js (/var/www/html/web/themes/custom/alps_trips/node_modules/postcss-loader/dist/utils.js:61:56)
    at Explorer.#loadConfiguration (/var/www/html/web/themes/custom/alps_trips/node_modules/cosmiconfig/dist/Explorer.js:116:42)
    at tryRunOrWebpackError (/var/www/html/web/themes/custom/alps_trips/node_modules/webpack/lib/HookWebpackError.js:88:9)
    at __webpack_require_module__ (/var/www/html/web/themes/custom/alps_trips/node_modules/webpack/lib/Compilation.js:5067:12)
    at __webpack_require__ (/var/www/html/web/themes/custom/alps_trips/node_modules/webpack/lib/Compilation.js:5024:18)
    at /var/www/html/web/themes/custom/alps_trips/node_modules/webpack/lib/Compilation.js:5095:20
    at symbolIterator (/var/www/html/web/themes/custom/alps_trips/node_modules/neo-async/async.js:3485:9)
    at done (/var/www/html/web/themes/custom/alps_trips/node_modules/neo-async/async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (/var/www/html/web/themes/custom/alps_trips/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/html/web/themes/custom/alps_trips/node_modules/tapable/lib/Hook.js:18:14)
    at /var/www/html/web/themes/custom/alps_trips/node_modules/webpack/lib/Compilation.js:5002:43
    at symbolIterator (/var/www/html/web/themes/custom/alps_trips/node_modules/neo-async/async.js:3482:9)
-- inner error --
Error: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
ReferenceError: tailwindcss is not defined
    at Object.<anonymous> (/var/www/html/web/themes/custom/alps_trips/postcss.config.js:3:14)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at module.exports (/var/www/html/web/themes/custom/alps_trips/node_modules/import-fresh/index.js:32:59)
    at Object.loadJsSync (/var/www/html/web/themes/custom/alps_trips/node_modules/cosmiconfig/dist/loaders.js:17:12)
    at .js (/var/www/html/web/themes/custom/alps_trips/node_modules/postcss-loader/dist/utils.js:61:56)
    at Explorer.#loadConfiguration (/var/www/html/web/themes/custom/alps_trips/node_modules/cosmiconfig/dist/Explorer.js:116:42)
    at Object.<anonymous> (/var/www/html/web/themes/custom/alps_trips/node_modules/css-loader/dist/cjs.js!/var/www/html/web/themes/custom/alps_trips/node_modules/postcss-loader/dist/cjs.js!/var/www/html/web/themes/custom/alps_trips/css/tailwind.css:1:7)
    at /var/www/html/web/themes/custom/alps_trips/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:452:10
    at Hook.eval [as call] (eval at create (/var/www/html/web/themes/custom/alps_trips/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/var/www/html/web/themes/custom/alps_trips/node_modules/tapable/lib/Hook.js:14:14)
    at /var/www/html/web/themes/custom/alps_trips/node_modules/webpack/lib/Compilation.js:5069:39
    at tryRunOrWebpackError (/var/www/html/web/themes/custom/alps_trips/node_modules/webpack/lib/HookWebpackError.js:83:7)
    at __webpack_require_module__ (/var/www/html/web/themes/custom/alps_trips/node_modules/webpack/lib/Compilation.js:5067:12)
    at __webpack_require__ (/var/www/html/web/themes/custom/alps_trips/node_modules/webpack/lib/Compilation.js:5024:18)
    at /var/www/html/web/themes/custom/alps_trips/node_modules/webpack/lib/Compilation.js:5095:20
    at symbolIterator (/var/www/html/web/themes/custom/alps_trips/node_modules/neo-async/async.js:3485:9)

Generated code for /var/www/html/web/themes/custom/alps_trips/node_modules/css-loader/dist/cjs.js!/var/www/html/web/themes/custom/alps_trips/node_modules/postcss-loader/dist/cjs.js!/var/www/html/web/themes/custom/alps_trips/css/tailwind.css
1 | throw new Error("Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):\nReferenceError: tailwindcss is not defined\n    at Object.<anonymous> (/var/www/html/web/themes/custom/alps_trips/postcss.config.js:3:14)\n    at Module._compile (node:internal/modules/cjs/loader:1198:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)\n    at Module.load (node:internal/modules/cjs/loader:1076:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:911:12)\n    at Module.require (node:internal/modules/cjs/loader:1100:19)\n    at module.exports (/var/www/html/web/themes/custom/alps_trips/node_modules/import-fresh/index.js:32:59)\n    at Object.loadJsSync (/var/www/html/web/themes/custom/alps_trips/node_modules/cosmiconfig/dist/loaders.js:17:12)\n    at .js (/var/www/html/web/themes/custom/alps_trips/node_modules/postcss-loader/dist/utils.js:61:56)\n    at Explorer.#loadConfiguration (/var/www/html/web/themes/custom/alps_trips/node_modules/cosmiconfig/dist/Explorer.js:116:42)");
 @ ./js/main.js 1:0-29

webpack 5.89.0 compiled with 2 errors in 235 ms
drew@packt-web:/var/www/html/web/themes/custom/alps_trips$ cd build/
drew@packt-web:/var/www/html/web/themes/custom/alps_trips/build$ ls
main.js  main.js.map

**Comment by lussoluca** [comment]
I'll look at this problem in the next few days; if you want to pass this point and go ahead, you can try to switch to the `final` branch, where everything is completed.

**Comment by BThvedt** [comment]
I had some similar issues, 

For the "The engine "node" is incompatible" issure I had to install nvm and use that to update to a version of node above 18. Then after I restarted the console yarn stopped working I had to use `npm install --global yarn` and restart the console again

And as for the top issue, renaming "main.css" (as it is in the book) to "tailwind.css"  fixed that. I didn't get any other issues and this has been enough to get me up through `yarn run build:dev` on page 38 so far haha

**Comment by alexb7217** [comment]
Same issue, same solution as @BThvedt : in `/web/themes/custom/alps_trips/js/main.js`:
Instead of:
```
import "../css/tailwind.css";
```
Use:
```
import "../css/main.css";
```

**Comment by lussoluca** [comment]
I've updated the yarn command here: https://github.com/PacktPublishing/Modernizing-Drupal-10-Theme-Development/blob/main/ERRATA.md#chapter-2 to fix required versions:

`yarn add -D webpack@5 webpack-cli@5 mini-css-extract-plugin@2 css-loader@6 postcss-loader@7`
